import AuthProvider from './AuthProvider';
import Navbar from './Navbar';
import './globals.css';
import { Open_Sans } from 'next/font/google';

const myFont = Open_Sans({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang='en'>
        <body className={myFont.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
